[package]
name = "rust-im"
version = "0.1.0"
edition = "2021"

[lib]


[dependencies]
fltk="1.3.25"
fltk-theme="0.6.0"
json = "0.12.4"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
painc = 'abort'